In [1]:
print("Hello World")

Hello World

In [2]:
import seaborn as sns
df = sns.load_dataset("titanic")
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [ ]:
import pandas as pd
import numpy as np
import re
from sklearn.preprocessing import LabelEncoder

# 1. Check for missing values and handle them.
df.isnull().sum()

survived         0
pclass           0
sex              0
age            177
sibsp            0
parch            0
fare             0
embarked         2
class            0
who              0
adult_male       0
deck           688
embark_town      2
alive            0
alone            0
dtype: int64

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [12]:
adult_male_avg = df.loc[df['adult_male'] == True, 'age'].mean()
overall_avg = df['age'].mean()

df.loc[(df['adult_male'] == True) & (df['age'].isnull()), 'age'] = adult_male_avg
df.loc[(df['adult_male'] == False) & (df['age'].isnull()), 'age'] = overall_avg

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

In [ ]:
df.loc[df['embarked']=="U"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True
829,1,1,female,62.0,0,0,80.0,NaN,First,woman,False,B,NaN,yes,True

In [17]:
df.loc[df['embarked'].isnull(), ['embarked', 'embark_town']] = ['U', 'Unknown']

In [18]:
df.loc[df['embarked']=="U"]

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
61,1,1,female,38.0,0,0,80.0,U,First,woman,False,B,Unknown,yes,True
829,1,1,female,62.0,0,0,80.0,U,First,woman,False,B,Unknown,yes,True

In [30]:
df['deck'] = df['deck'].cat.add_categories('U')
df.loc[df['deck'].isnull(), 'deck'] = 'U'

In [31]:
df.loc[df['deck'].notnull()].groupby('deck').size()

C:\Users\Admin\AppData\Local\Temp\ipykernel_11588\771941676.py:1: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  df.loc[df['deck'].notnull()].groupby('deck').size()

deck
A     15
B     47
C     59
D     33
E     32
F     13
G      4
U    688
dtype: int64

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     891 non-null    object
 8   class        891 non-null    category
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         891 non-null    category
 12  embark_town  891 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB

# 2. Check for duplicate rows and remove them.

In [34]:
df[df.duplicated(keep=False)]
df.drop_duplicates(inplace=True)

# 3. Inspect the "Sex" column for inconsistencies and standardize values.

In [42]:
df['sex'].value_counts(dropna=False)

sex
male      491
female    293
Name: count, dtype: int64

In [43]:
df.groupby(['sex', 'who']).size()

sex     who
female  child     42
        woman    251
male    child     40
        man      451
dtype: int64

In [ ]:
# 4. Detect and handle outliers in the "Age" and "Fare" columns.
for col in ['age', 'fare']:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    df[col] = df[col].clip(lower=lower, upper=upper)

df[['age', 'fare']].describe()
# 5. Create a new "Family_Size" feature based on "SibSp" and "Parch".
df['family_size'] = df['sibsp'] + df['parch'] + 1 

# 6. Convert the "Embarked" column to numerical values using label encoding.
le = LabelEncoder()
df['embarked'] = le.fit_transform(df['embarked'])

# 7. If a "Ticket_Purchase_Date" column existed, convert it to datetime and extract the year and month.

In [58]:
start = pd.Timestamp('1912-01-01')
end = pd.Timestamp('1912-04-10')  # day tickets stopped being sold

date_range_days = (end - start).days
random_days = np.random.randint(0, date_range_days, size=len(df))
df['Ticket_Purchase_Date'] = start + pd.to_timedelta(random_days, unit='D')
df['purchase_year'] = df['Ticket_Purchase_Date'].dt.year
df['purchase_month'] = df['Ticket_Purchase_Date'].dt.month

In [55]:
# 8. Clean the "Name" column by removing titles and converting to lowercase.
'Name' in df.columns

# 9. Bin the "Age" column into categories like 'Child', 'Teen', 'Adult', and 'Senior'.
bins = [0, 12, 18, 35, 60, 100]
labels = ['child', 'teenager', 'young adult', 'adult', 'senior']

df['age_group'] = pd.cut(df['age'], bins=bins, labels=labels)

In [57]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,Ticket_Purchase_Date,purchase_year,purchase_month,age_group
0,0,3,male,22.0,1,0,7.2500,2,Third,man,True,U,Southampton,no,False,2,1912-01-07,1912,1,young adult
1,1,1,female,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False,2,1912-02-19,1912,2,adult
2,1,3,female,26.0,0,0,7.9250,2,Third,woman,False,U,Southampton,yes,True,1,1912-01-13,1912,1,young adult
3,1,1,female,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False,2,1912-02-19,1912,2,young adult
4,0,3,male,35.0,0,0,8.0500,2,Third,man,True,U,Southampton,no,True,1,1912-02-11,1912,2,young adult

# function that takes data and gets rid of nulls
# goes through all columns, if the numerical columns are an outlier

In [65]:
def nullremover(sourcedf):
    return sourcedf.dropna().drop_duplicates(inplace=True)

In [66]:
nullremover(df)

In [61]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   survived              784 non-null    int64
 1   pclass                784 non-null    int64
 2   sex                   784 non-null    object
 3   age                   784 non-null    float64
 4   sibsp                 784 non-null    int64
 5   parch                 784 non-null    int64
 6   fare                  784 non-null    float64
 7   embarked              784 non-null    int32
 8   class                 784 non-null    category
 9   who                   784 non-null    object
 10  adult_male            784 non-null    bool
 11  deck                  784 non-null    category
 12  embark_town           784 non-null    object
 13  alive                 784 non-null    object
 14  alone                 784 non-null    bool
 15  family_size           784 non-null    int64
 16  Ticket_Purchase_Date  784 non-null    datetime64[ns]
 17  purchase_year         784 non-null    int32
 18  purchase_month        784 non-null    int32
 19  age_group             784 non-null    category
dtypes: bool(2), category(3), datetime64[ns](1), float64(2), int32(3), int64(5), object(4)
memory usage: 93.3+ KB

In [75]:
def outlierremover(sourcedf):
    # Identifying the numeric cols
    col_list = list(sourcedf.select_dtypes(include=['int64', 'float64']).columns)

    for col in col_list:
        Q1 = sourcedf[col].quantile(0.25)
        Q3 = sourcedf[col].quantile(0.75)
        IQR = Q3 - Q1
        lower = Q1 - 1.5 * IQR
        upper = Q3 + 1.5 * IQR
        cleandf = sourcedf[(sourcedf[col] >= lower) & (sourcedf[col] <= upper)]
        outlierdf = sourcedf[(sourcedf[col] < lower) & (sourcedf[col] > upper)]
    return cleandf, outlierdf

In [76]:
clean, source = outlierremover(df)

In [74]:
clean.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,family_size,Ticket_Purchase_Date,purchase_year,purchase_month,age_group
0,0,3,male,22.0,1,0,7.2500,2,Third,man,True,U,Southampton,no,False,2,1912-01-06,1912,1,young adult
1,1,1,female,38.0,1,0,71.2833,0,First,woman,False,C,Cherbourg,yes,False,2,1912-04-06,1912,4,adult
2,1,3,female,26.0,0,0,7.9250,2,Third,woman,False,U,Southampton,yes,True,1,1912-02-29,1912,2,young adult
3,1,1,female,35.0,1,0,53.1000,2,First,woman,False,C,Southampton,yes,False,2,1912-01-27,1912,1,young adult
4,0,3,male,35.0,0,0,8.0500,2,Third,man,True,U,Southampton,no,True,1,1912-01-17,1912,1,young adult

In [64]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 784 entries, 0 to 890
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   survived              784 non-null    int64
 1   pclass                784 non-null    int64
 2   sex                   784 non-null    object
 3   age                   784 non-null    float64
 4   sibsp                 784 non-null    int64
 5   parch                 784 non-null    int64
 6   fare                  784 non-null    float64
 7   embarked              784 non-null    int32
 8   class                 784 non-null    category
 9   who                   784 non-null    object
 10  adult_male            784 non-null    bool
 11  deck                  784 non-null    category
 12  embark_town           784 non-null    object
 13  alive                 784 non-null    object
 14  alone                 784 non-null    bool
 15  family_size           784 non-null    int64
 16  Ticket_Purchase_Date  784 non-null    datetime64[ns]
 17  purchase_year         784 non-null    int32
 18  purchase_month        784 non-null    int32
 19  age_group             784 non-null    category
dtypes: bool(2), category(3), datetime64[ns](1), float64(2), int32(3), int64(5), object(4)
memory usage: 93.3+ KB

In [77]:
inputlist = [13, 456, 76, 888, 9877, 12, 344, 53, 2]

In [99]:
def quicksort(inlist):
    listlen = len(inlist)
    while not all(inlist[index] < inlist[index + 1] for index in range(0, listlen-1)):
        for index in range(0, listlen-1):
            i = inlist[index]
            j = inlist[index + 1]
            if i > j:
                inlist[index], inlist[index + 1] = inlist[index + 1], inlist[index]
    return inlist

In [98]:
quicksort(inputlist)

[2, 12, 13, 53, 76, 344, 456, 888, 9877]